services:
  lackey:
    platform: linux/amd64
    container_name: lackey
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5901:5901"
      - "8080:8080"
      - "3389:3389"
    environment:
      VNC_PASSWORD: asdfasdf
      DISPLAY: :1
    networks:
      - lackey
    volumes:
      - plugins:/app/LackeyCCG/plugins
      - secure:/app/LackeyCCG/secure
networks:
  lackey:
volumes:
  plugins:
  secure:
