FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
  curl \
  dbus-x11 \
  wine \
  net-tools \
  unzip \
  xfce4 \
  tightvncserver

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

