#!/bin/bash
xrdb $HOME/.Xresources

export DISPLAY=:1

startxfce4 &

#Start PulseAudio Server
pulseaudio -D

#Initialize Wine and open Notepad
#wine /app/.wine/drive_c/windows/system32/notepad.exe
#sleep 15



#while true; do
#  cd /app/LackeyCCG && WINEDEBUG=+all wine Z:\\app\\LackeyCCG\\LackeyCCG.exe >>wine_debug.log 2>&1
#done
